### ISSUE TITLE
Error when running CSS

### ISSUE THREAD

**Issue by pheyvaer** [argahsuknesib/query-equivalence-demo#1]
When I start the CSS with `npm run start-solid-server` I get the following error

```shell
> query-equivalence-demo@1.0.0 start-solid-server
> cd scripts && rm -rf data/.internal/ && npx community-solid-server --config ./pod/config/unsafe.json -f ./data/ --seededPodConfigJson ./pod/multiSolidPod.json

oidc-provider WARNING: Unsupported Node.js runtime version. Use ^12.19.0, ^14.15.0, or ^16.13.0
2023-06-28T14:31:14.131Z [Components.js] info: Initiating component discovery from /Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/@solid/community-server/
node ./bin/server.js [args]

Options:
      --version         Show version number                            [boolean]
  -c, --config
  [array] [default: ["/Users/pheyvaer/Development/solidlab/query-equivalence-dem
                   o/node_modules/@solid/community-server/config/default.json"]]
  -l, --loggingLevel
        [string] [choices: "error", "warn", "info", "verbose", "debug", "silly"]
                                                               [default: "info"]
  -m, --mainModulePath                                                  [string]

Could not build the config files from /Users/pheyvaer/Development/solidlab/query-equivalence-demo/scripts/pod/config/unsafe.json
Cause: Error while parsing import path 'https://linkedsoftwaredependencies.org/bundles/npm/@treecg/versionawareldesinldp/^0.0.0/config/' in /Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/@treecg/versionawareldesinldp: /Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/@treecg/versionawareldesinldp/config/ does not exist.
Error: Error while parsing import path 'https://linkedsoftwaredependencies.org/bundles/npm/@treecg/versionawareldesinldp/^0.0.0/config/' in /Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/@treecg/versionawareldesinldp: /Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/@treecg/versionawareldesinldp/config/ does not exist.
    at /Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/componentsjs/lib/loading/ModuleStateBuilder.js:289:35
    at async Promise.all (index 323)
    at async ModuleStateBuilder.buildComponentImportPaths (/Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/componentsjs/lib/loading/ModuleStateBuilder.js:274:9)
    at async ModuleStateBuilder.buildModuleState (/Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/componentsjs/lib/loading/ModuleStateBuilder.js:30:29)
    at async ComponentsManagerBuilder.build (/Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/componentsjs/lib/loading/ComponentsManagerBuilder.js:63:27)
    at async AppRunner.createComponentsManager (/Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/@solid/community-server/dist/init/AppRunner.js:151:35)
    at async AppRunner.createCli (/Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/@solid/community-server/dist/init/AppRunner.js:135:33)
    at async AppRunner.runCli (/Users/pheyvaer/Development/solidlab/query-equivalence-demo/node_modules/@solid/community-server/dist/init/AppRunner.js:100:21)
```

I did `npm i`.

**Comment by argahsuknesib** [comment]
It is due to the @treecg/versionawareldesinldp library not having the /config/ folder. Should be fixed with the recent commit. fb3d7bae9555bf7de65e9296b5f8a6aeaabc04d7
